image: python:3.9-slim

stages:
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

pypi:
  stage: deploy
  script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - source $HOME/.poetry/env
    - poetry install
    - poetry config pypi-token.pypi $PYPI_TOKEN
    - poetry publish --build
  only:
    - master
  environment:
    name: pypi
    url: https://pypi.org/project/collectors-channel-cli
